config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :comments
    resource :cover_image, only: [:destroy], module: :posts
    post "repost", on: :member
  end

  resources :likes, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy, :index]
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get "pages/home"
  
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get '/people/suggestions', to: 'pages#suggestions', as: 'suggestions'
  get '/following/posts', to: 'pages#follower_posts', as: 'follwers_post'
  get '/:id/followers', to: 'pages#followers', as: 'followers'
  get '/:id/following', to: 'pages#following', as: 'following'
  get '/notifications', to: 'pages#notification', as: 'notification'
  get '/posts/:id/comment', to: 'pages#comments', as: 'list_comments'
  get '/follow/notifications', to: 'pages#notification_reqs', as: 'request_notification'

  get 'edit_personal_details', to: 'pages#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'pages#update_personal_details', as: 'update_member_personal_details'

  post 'followability/:id/follow', to: 'followability#follow', as: 'follow'
  post 'followability/:id/unfollow', to: 'followability#unfollow', as: 'unfollow'
  post 'followability/:id/accept', to: 'followability#accept', as: 'accept'
  post 'followability/:id/decline', to: 'followability#decline', as: 'decline'
  post 'followability/:id/cancel', to: 'followability#cancel', as: 'cancel'
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/pages/_follow_reqs.html.erb
<p class="text-center text-muted fw-light">All activities releted to your connection will pop here!</p>
<div class="row">
  <div >
    <div class="container my-3 p-3 bg-body rounded shadow-sm">
      <h6 class="border-bottom pb-2 mb-0 text-muted">Recent Requests</h6>
      <% current_user.follow_requests.each do |request| %>
        <div class="d-flex justify-content-between text-body-secondary pt-3 border-bottom">
          <div class="pb-3 mb-0 small lh-sm">
            <strong class="text-gray-dark"><%= link_to request.followerable.name, profile_path(request.followerable.id) %></strong>
            requested to follow you. <small class="fw-light">(<%= time_ago_in_words(request.created_at)+ ' ago' %>)</small>
          </div>
          <div class="req_actions d-flex mb-2">
            <%= button_to "Accept", accept_path(request.followerable), class:'btn btn-primary btn-sm' %>
            <%= button_to "Decline", decline_path(request.followerable), class:'btn btn-danger mx-1 btn-sm' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div>
    <div class="container my-3 p-3 bg-body rounded shadow-sm">
      <h6 class="border-bottom pb-2 mb-0 text-muted">Recent Followers</h6>
      <% if current_user.followers.count > 0%>
        <% current_user.followers.each do |user| %>
          <div class="d-flex text-body-secondary border-bottom pt-3">
            <p class="pb-3 mb-0 small lh-sm ">
              <strong class="d-flex gap-4 text-gray-dark">
                <%= user.email %>
                <span class="badge text-bg-danger">New</span>
              </strong>
              started following you...
            </p>
          </div>
        <% end %>
      <% else %>
        <h2 class="fw-bold mt-3 text-muted">No Recent followers.</h2>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_following.html.erb
<% @following.each do |user| %>
  <div class="d-flex gap-2">
    <div class="user_image">
      <%= image_tag(user.image.attached? ? user.image : 'https://avatars.githubusercontent.com/u/116902652?v=', width: "32", height: '32', class: 'rounded-circle')%>
    </div>
    <div class="user_details d-flex flex-column">
      <b><%= link_to user.email, profile_path(user.id) %></b>
      <small class="text-muted fw-light">
        Posts <%= user.posts.count %> | <%= time_ago_in_words(user.created_at) + ' ago'%>
      </small>
    </div>
  </div>
  <hr>
<% end %>

app/views/pages/_paths.html.erb
<%= render 'layouts/return_home' %>
<% items = [
  ['Post', notification_path],
  ['Requests',request_notification_path]
]%>
<div class="text-end mx-4">
  <%= select_tag nil, options_for_select(items,request.path),onchange: "Turbo.visit(this.selectedOptions[0].value)", class: 'btn btn-primary '%>
</div>

app/views/pages/comments.html.erb
<div class="container mt-5">
  <% @comment.each do |comment| %>
    <%= render 'comments/comments', comment: comment%>
  <% end %>
</div>

app/views/pages/edit_personal_details.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do%>
  <%= render 'layouts/form_modal', modal_title: 'Edit your personal details', form_partial: 'pages/personal_info_modal' %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/pages/follower_posts.html.erb
<% content_for(:html_title) { 'For You' } %>
<%= render 'layouts/return_home' %>
<h3 class="text-center text-muted fw-bold mt-5">Following</h3>
<p class="text-center text-muted fw-light ">All your followers posts will pop here!</p>
<hr>
<% @users.each do |user| %>
  <% user.posts.each do |post| %>
    <div class="mb-4">
      <%= render post%>
    </div>
  <% end %>
<% end %>

app/views/pages/following.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'layouts/form_modal', modal_title: 'Followers', form_partial: 'pages/following' %>
<% end %>

app/views/pages/notification.html.erb
<div class="container mt-5">
  <%= render "notifications/notifications", user: current_user %>
</div>

app/views/pages/notification.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do%>
  <%= render 'layouts/form_modal', modal_title: 'Notifications', form_partial: 'pages/notifications' %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/pages/notification_reqs.html.erb
<div class="mt-5">
  <%= render 'pages/follow_reqs'%>
</div>

app/views/pages/profile.html.erb
<% content_for(:html_title) { "#{@user.name}" } %>
<%= render 'layouts/return_home' %>
<section class="section about-section gray-bg" id="about">
  <div class="container">
    <div class="row align-items-center flex-row-reverse">
      <div class="col-lg-6">
        <div class="about-text go-to">
          <h3 class="dark-color"><%= @user.email %></h3>
          <h6 class="theme-color lead">Joined  <%= time_ago_in_words(@user.created_at) + ' ago'%></h6>
          <hr>
          <div class="d-flex gap-5">
            <div class="d-flex text-center flex-column">
              <h4><%= @user.followers.count %></h4>
              <div class="text-muted">
                <%= link_to 'Followers', followers_path, data: { controller: 'bs-modal' } %>
              </div>
            </div>
            <div class="d-flex text-center flex-column">
              <h4><%= @user.following.count %></h4>
              <div class="text-muted">
                <%= link_to 'Following', following_path, data: { controller: 'bs-modal' } %>
              </div>
            </div>
          </div>
          <hr>
          <% if current_user.id != @user.id%>
            <% if current_user.following?(@user) %>
              <%= button_to "Unfollow", unfollow_path(@user), class:'btn btn-danger w-100 mt-2 mb-2' %>
            <% elsif current_user.sent_follow_request_to?(@user)%>
              <%= button_to "Cancel follow request", cancel_path(@user), class:'btn btn-danger w-100 mt-2 mb-2' %>
            <% else %>
              <%= button_to "Follow",  follow_path(@user), class:'btn btn-primary w-100 mt-2 mb-2' %>
            <% end %>
          <% end %>
          <p>I <mark>design and develop</mark> services for customers of all sizes, specializing in creating stylish, modern websites, web services and online stores. My passion is to design digital user experiences through the bold interface and meaningful interactions.</p>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="about-avatar">
          <%= image_tag(@user.image.attached? ? @user.image : 'https://avatars.githubusercontent.com/u/116902652?v=', width: "450px", height: '450px', class: 'rounded-circle mb-4')%>
        </div>
      </div>
    </div>
    <div class="counter">
      <div class="row">
        <div class="col-6 col-lg-3">
          <div class="count-data text-center">
            <h6 class="count h2" data-to="500" data-speed="500"><%= @user.posts.count %></h6>
            <p class="m-0px font-w-600">Posts</p>
          </div>
        </div>
        <div class="col-6 col-lg-3">
          <div class="count-data text-center">
            <h6 class="count h2" data-to="150" data-speed="150">150</h6>
            <p class="m-0px font-w-600">Project Completed</p>
          </div>
        </div>
        <div class="col-6 col-lg-3">
          <div class="count-data text-center">
            <h6 class="count h2" data-to="850" data-speed="850"><%= @user.likes.count %></h6>
            <p class="m-0px font-w-600">Likes Count</p>
          </div>
        </div>
        <div class="col-6 col-lg-3">
          <div class="count-data text-center">
            <h6 class="count h2" data-to="190" data-speed="190"><%= time_ago_in_words(@user.created_at)%></h6>
            <p class="m-0px font-w-600">Joined</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/suggestions.html.erb
<div class="container">
  <div class="p-2">
    <%= link_to :back do %>
      <i class="bi bi-arrow-left h3"></i>
    <% end %>
  </div>
  <h3 class="text-center text-muted fw-bold mt-5">Suggested</h3>
  <p class="text-center text-muted fw-light ">Suggestions for <%= current_user.email %></p>
  <hr>
  <% users_not_followed.each do |user|%>
    <%= render 'posts/suggested_users', user: user %>
  <% end %>
</div>

app/views/pages/suggestions.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do%>
  <%= render 'layouts/form_modal', modal_title: 'Suggested Users', form_partial: 'pages/suggestions' %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/pages/update_personal_details.turbo_stream.erb
<%= turbo_stream.update "user_details" do %>
  <%= render 'posts/user_details' %>
<% end %>
<%= render_turbo_stream_flash_messages %>