config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :comments
    resource :cover_image, only: [:destroy], module: :posts
    post "repost", on: :member
  end

  resources :likes, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy, :index]
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get "pages/home"
  
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get '/people/suggestions', to: 'pages#suggestions', as: 'suggestions'
  get '/following/posts', to: 'pages#follower_posts', as: 'follwers_post'
  get '/:id/followers', to: 'pages#followers', as: 'followers'
  get '/:id/following', to: 'pages#following', as: 'following'
  get '/notifications', to: 'pages#notification', as: 'notification'
  get '/posts/:id/comment', to: 'pages#comments', as: 'list_comments'
  get '/follow/notifications', to: 'pages#notification_reqs', as: 'request_notification'

  get 'edit_personal_details', to: 'pages#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'pages#update_personal_details', as: 'update_member_personal_details'

  post 'followability/:id/follow', to: 'followability#follow', as: 'follow'
  post 'followability/:id/unfollow', to: 'followability#unfollow', as: 'unfollow'
  post 'followability/:id/accept', to: 'followability#accept', as: 'accept'
  post 'followability/:id/decline', to: 'followability#decline', as: 'decline'
  post 'followability/:id/cancel', to: 'followability#cancel', as: 'cancel'
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  has_many_attached :images
  belongs_to :user

  with_options dependent: :destroy do
    has_many :comments
    has_many :likes
    has_many :bookmarks
  end

  validates :title, presence: true
  validate :validate_image_format

  def validate_image_format
    images.each do |image|
      unless image.blob.content_type.in?(%w[image/jpeg image/png])
        errors.add(:images, 'must be a JPEG or PNG image')
      end
    end
  end

end

app/controllers/posts/cover_images_controller.rb
class Posts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!
  before_action :set_post

  def destroy
    @post.images.purge_later
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.remove(dom_id(@post, :cover_image))
      }
      format.html { redirect_to edit_post_path(@post) }
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy repost ]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order('Created_at DESC')

    if current_user
      @notifications = current_user.notifications.limit(3)
      current_user.notifications.mark_as_read!
    end
  end

  def repost
    @new_post = @post.dup
    @new_post.update(user_id: current_user.id) 
    @new_post.update(reposted: true) 

    respond_to do |format|
      if @new_post.save
        format.turbo_stream { flash.now[:notice] = "Post #{@post.title} reposted" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    @comment = @post.comments.order("Created_at DESC")
    @post.update(views: @post.views + 1)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream { flash.now[:notice] = "Post was successfully created." }
      else
        format.turbo_stream { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.turbo_stream { flash.now[:notice] = "Post was successfully updated!" }
      else
        format.turbo_stream { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Post was successfully destroyed." }
    end
  end

  private

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_path,alert: "Not Authorized!" if @post.nil?
  end

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :reposted, :reposted_from, :user_id, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_action_buttons.html.erb
<div class="container">
  <hr>
  <div class="d-flex gap-5 align-items-center justify-content-between ">
    <div class="post_actions">
      <div class="d-flex gap-5 align-items-center">
        <div class="likes">
          <% like = current_user.likes.find_by(post: post) %>
          <% if like.nil? %>
            <%= button_to likes_path, params: { like: { post_id: post.id } }, method: :post, class: 'btn' do %>
              <div class="d-flex align-items-center">
                <i class="bi bi-heart h3" style="color: red;"></i>
                <span class="mx-2 h5 fw-light text-danger"><%= pluralize(post.likes.count, 'like') %></span>
              </div>
            <% end %>
          <% else %>
            <%= button_to like_path(like), method: :delete, class: 'btn' do %>
              <div class="d-flex align-items-center">
                <i class="bi bi-heart-fill h3" style="color: red;"></i>
                <span class="mx-2 h5 fw-light text-danger"><%= pluralize(post.likes.count, 'like') %></span>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="comment">
          <div class="d-flex align-items-center">
            <i class="<%=  post.comments.count > 0 ? 'bi bi-chat-right-text-fill' : 'bi bi-chat-right-text'%> h3"></i>
            <span class="mx-2 h5 fw-light"><%= link_to pluralize(post.comments.count, 'Replies'), choose_path(post), class: "text-decoration-none", data: { controller: stimulus_controller } %></span>
          </div>
        </div>
        <div class="repost">
          <%= link_to repost_post_path(post), data: { turbo_method: :post }, class: 'btn' do %>
            <i class="bi bi-shuffle h3"></i>
            <span class="mx-2 h5 fw-light">Repost</span>
          <% end %>
        </div>
        <div class="bookmark" id="bookmark">
          <%= render 'posts/bookmark', post: post %>
        </div>
      </div>
    </div>
    <div class="avatars">
      <% if post.likes.present? %>
        <div class="user-avatars">
          <% post.likes.each do |like| %>
            <%= link_to image_tag(like.user.image.attached? ? like.user.image : 'https://avatars.githubusercontent.com/u/116902652?v=', size: '20x20', class: ' rounded-circle mx-1'), profile_path(like.user.id), data: { turbo_frame: '_top' } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
</div>

app/views/posts/_bookmark.html.erb
<% bookmark = current_user.bookmarks.find_by(post: post) %>
<% if bookmark.nil? %>
  <%= button_to bookmarks_path, params: { bookmark: { post_id: post } }, method: :post, class: 'btn' do %>
    <div class="d-flex align-items-center">
      <i class="bi bi-bookmark h3"></i>
      <span class="mx-2 h5 fw-light"></span>
    </div>
  <% end %>
<% else %>
  <%= button_to bookmark_path(bookmark), params: { bookmark: { post_id: post } }, method: :delete, class: 'btn' do %>
    <div class="d-flex align-items-center">
      <i class="bi bi-bookmark-fill h3"></i>
    </div>
  <% end %>
<% end %>

app/views/posts/_follow_reqs.html.erb
<div class="container my-3 p-3 bg-body rounded shadow-sm">
  <h6 class="border-bottom pb-2 mb-0 mt-4">Recent updates</h6>
  <% current_user.follow_requests.limit(3).each do |request| %>
    <div class="d-flex justify-content-between text-body-secondary pt-3 border-bottom">
      <div class="pb-3 mb-0 small lh-sm">
        <strong class="text-gray-dark"><%= link_to request.followerable.name, profile_path(request.followerable.id) %></strong>
        requested to follow you. <small class="fw-light">(<%= time_ago_in_words(request.created_at)+ ' ago' %>)</small>
      </div>
      <div class="req_actions d-flex mb-2">
        <%= button_to "Accept", accept_path(request.followerable), class:'btn btn-primary btn-sm' %>
        <%= button_to "Decline", decline_path(request.followerable), class:'btn btn-danger mx-1 btn-sm' %>
      </div>
    </div>
  <% end %>
  <small class="d-block text-end mt-3">
    <a href="/notifications">All updates</a>
  </small>
</div>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_with(model: @post) do |form| %>
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: 'form-control mt-2' %>
      <% if @post.errors.any? %>
        <% @post.errors.full_messages_for(:title).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      <% end %>
    </div>
    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body, class: 'form-control mt-2', cols: 4,  rows: "6"%>
    </div>
    <%  if @post.images.attached? %>
      <div id="<%= dom_id(@post, :cover_image) %>">
        <% @post.images.each do |image| %>
          <%= image_tag(image, width: '50px', height: '50px', class: ' mt-2 mb-2') %>
        <% end %>
        <%= link_to 'Remove Images', post_cover_image_path(@post), data: { turbo_method: :delete, turbo_confirm: 'You sure?' }, class: 'mx-2' %>
      </div>
    <% end %>
    <div>
      <%= form.file_field :images, type: "file", class: "form-control mt-2", id: "customFile", multiple: true, data: { controller: "handle-upload" } %>
    </div>
    <div>
      <%= form.number_field :user_id, value: current_user.id, id: 'post_user_id',class: 'form-control mt-2',type: :hidden%>
    </div>
    <% unless @post.persisted? %>
      <div>
        <%= form.number_field :reposted_from, value: current_user.id, id: 'post_user_id',class: 'form-control mt-2', type: :hidden %>
      </div>
    <% end %>
    <div>
      <%= form.submit class: 'btn btn-primary mt-2', data: { action: 'click->bootstrap#submitEnd'} %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<%= turbo_frame_tag post do %>
  <div class="container mb-3">
    <div class="d-flex justify-content-between">
      <div class="d-flex text-align-center gap-2">
        <div class="user_post_image mt-2">
          <%= image_tag(post.user.image.attached? ? post.user.image : 'https://avatars.githubusercontent.com/u/116902652?v=', width: "32", height: '32', class: 'rounded-circle')%>
        </div>
        <div class="d-flex flex-column">
          <div class="user_email">
            <%= link_to post.user.email, profile_path(post.user), data: { turbo_frame: '_top'}, class: 'text-decoration-none text-dark'%>
          </div>
          <div class="post_time">
            <p><small class="text-muted"><%= time_ago_in_words(post.created_at)+ ' ago'%></small></p>
          </div>
        </div>
      </div>
      <% if current_user.id == post.user.id %>
        <div class="actions">
          <div class="dropdown">
            <button class="btn btn " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-three-dots"></i>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li><%= link_to 'Edit', edit_post_path(post), data: { controller: 'bs-modal'} , class: 'dropdown-item' %></li>
              <li><%= button_to 'Destroy', post_path(post), method: :delete, class: 'dropdown-link btn btn' %></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <% if post.reposted? %>
      <h6 class="text-muted repost-badge d-flex justify-content-center align-items-center">
        Reposted from <i class="bi bi-shuffle mx-2"></i>
        <b><%= User.find(post.reposted_from).email %></b>
      </h6>
    <% end %>
    <h5 class="p-1"><%= link_to post.title, post, data: { turbo_frame: '_top' }, class: 'text-decoration-none text-dark' %>
    </h5>
    <p class="p-1"><%= link_to simple_format(post.body), post, data: { turbo_frame: '_top' }, class: 'text-decoration-none text-dark' if !post.images.attached? %></p>
    <% if post.images.attached?  %>
      <div class="post_images">
        <% post.images.each do |image| %>
          <div class="image_container">
            <%= link_to image_tag(image, class: 'post_image'), post_path(post), data: { turbo_frame: '_top' } %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= render 'posts/action_buttons', post: post %>
<% end %>

app/views/posts/_suggested_users.html.erb
<div class="d-flex justify-content-between align-items-center">
  <div class="main d-flex align-items-center gap-2">
    <div class="user_image">
      <%= image_tag(user.image.attached? ? user.image : 'https://avatars.githubusercontent.com/u/116902652?v=', size: "35x35", class: 'rounded-circle')%>
    </div>
    <div class="user_details">
      <%= link_to user.email, profile_path(user.id), data: { turbo_frame: '_top'} %>
      <br>
      <small class="text-muted">Joined: <%= time_ago_in_words(user.created_at) + ' ago'%> | <%= pluralize(user.posts.count, 'post') %></small>
    </div>
  </div>
  <div class="actions">
    <%= turbo_frame_tag dom_id(user, :suggested) do %>
      <% if current_user.id != user.id%>
        <% if current_user.following?(user) %>
          <%= button_to "Unfollow", unfollow_path(user), class:'btn btn-danger w-100 mt-2 mb-2' %>
        <% elsif current_user.sent_follow_request_to?(user)%>
          <%= button_to "Cancel follow request", cancel_path(user), class:'btn btn-danger w-100 mt-2 mb-2' %>
        <% else %>
          <%= button_to "Follow",  follow_path(user), class:'btn btn-primary w-100 mt-2 mb-2' %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<hr>

app/views/posts/_suggestions.html.erb
<div class="texts d-flex justify-content-between">
  <p class="fw-bold text-muted mt-5 mb-4">Suggested for you</p>
  <p class="fw-bold mt-5 mb-4"><%= link_to 'See All', suggestions_path, data: { controller: 'bs-modal' } %></p>
</div>
<% users_not_followed.limit(2).each do |user|%>
  <%= render 'suggested_users', user: user %>
<% end %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag @post do %>
  <%= render "form", post: @post %>
  <hr>
<% end %>

app/views/posts/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'layouts/form_modal', modal_title: 'Edit your post!', form_partial: 'posts/form' %>
<% end %>

app/views/posts/index.html.erb
<% content_for(:html_title) { 'Homepage' } %>
<div class="p-4">
  <div class="row">
    <div class="col-lg-9 ">
      <%= render 'posts/status_box' %>
      <hr>
      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <%= render 'posts/search'%>
      </form>
      <hr>
      <div class="text-center">
        <h3 class="text-muted fw-bold">Timeline </h3>
        <small class="text-center text-muted">Last Refreshed <%= Time.now.strftime('%I:%M:%S %p') %></small>
        <hr>
      </div>
      <div id="posts">
        <% @posts.each do |post| %>
          <%= render post, post: post %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3 border">
      <%= render 'posts/user_details'%>
      <div class="container">
        <%= render 'posts/suggestions'%>
      </div>
      <br>
      <% if current_user.posts.count > 0 %>
        <%= turbo_frame_tag "notifications" do %>
          <%= render "notifications/notifications", user: current_user %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag @post do %>
  <%= render "form", post: @post %>
<% end %>

app/views/posts/repost.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <%= render 'posts/post', post: @new_post %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/posts/show.html.erb
<% content_for(:html_title) { "#{@post.title.first(10)}...." } %>
<%= render 'layouts/return_home' %>
<%= render @post %>
<div class="container">
  <%= render 'comments/comments'%>
</div>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.update @post %>
<%= render_turbo_stream_flash_messages %>