config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :comments
    resource :cover_image, only: [:destroy], module: :posts
    post "repost", on: :member
  end

  resources :likes, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy, :index]
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get "pages/home"
  
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get '/people/suggestions', to: 'pages#suggestions', as: 'suggestions'
  get '/following/posts', to: 'pages#follower_posts', as: 'follwers_post'
  get '/:id/followers', to: 'pages#followers', as: 'followers'
  get '/:id/following', to: 'pages#following', as: 'following'
  get '/notifications', to: 'pages#notification', as: 'notification'
  get '/posts/:id/comment', to: 'pages#comments', as: 'list_comments'
  get '/follow/notifications', to: 'pages#notification_reqs', as: 'request_notification'

  get 'edit_personal_details', to: 'pages#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'pages#update_personal_details', as: 'update_member_personal_details'

  post 'followability/:id/follow', to: 'followability#follow', as: 'follow'
  post 'followability/:id/unfollow', to: 'followability#unfollow', as: 'unfollow'
  post 'followability/:id/accept', to: 'followability#accept', as: 'accept'
  post 'followability/:id/decline', to: 'followability#decline', as: 'decline'
  post 'followability/:id/cancel', to: 'followability#cancel', as: 'cancel'
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove" >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_form_modal.html.erb
<%= turbo_frame_tag "remote_modal", target: '_top' do %>
  <div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" data-controller="bootstrap">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel"><%= modal_title %></h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render form_partial %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2  text-light text-uppercase"> Home</a></li>
          <li><a href="/bookmarks" class="mx-2 nav-link px-2  text-light text-uppercase"> Bookmarked</a></li>
          <% if current_user.followers.count > 0 %>
            <li><%= link_to 'Following', follwers_post_path, class: 'nav-link text-light text-uppercase' %></li>
          <% end %>
        </ul>
        <%= link_to request_notification_path, class: 'position-relative text-white mx-4', data: { controller: 'bs-modal' } do%>
          <i class="bi bi-people-fill h4"></i>
          <span class="position-absolute left-0 start-100 translate-middle badge rounded-pill bg-danger">
            <%= connection_notifications %>
            <span class="visually-hidden">unread messages</span>
          </span>
        <% end %>
        <%= link_to notification_path, class: 'position-relative text-white mx-4', data: { controller: 'bs-modal' } do%>
          <i class="bi bi-bell-fill h4"></i>
          <span class="position-absolute left-0 start-100 translate-middle badge rounded-pill bg-danger">
            <%= post_notifications %>
            <span class="visually-hidden">unread messages</span>
          </span>
        <% end %>
        <div class="dropdown text-end">
          <a href="#" class="d-block  text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="mx-2 text-light"><%= current_user.name %></span>
            <%= image_tag(current_user.image.attached? ? current_user.image : 'https://avatars.githubusercontent.com/u/116902652?v=', width: "32", height: '32', class: 'rounded-circle')%>
          </a>
          <ul class="dropdown-menu text-small">
            <li><%= link_to 'Profile', profile_path(current_user), class: 'dropdown-item' %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item text-danger' %></li>
          </ul>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/layouts/_return_home.html.erb
<div class="p-2">
  <%= link_to root_path, class: 'text-decoration-none' do %>
    <div class="d-flex align-items-center gap-1">
      <div><i class="bi bi-arrow-left h3 text-decoration-none !important"></i></div>
      <span class="fw-light"> Return Home</span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:html_title) %> Connect Me</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>
    <%= turbo_frame_tag "remote_modal" %>
    <%= yield %>
  </body>
</html>